#
# Copyright (C) 2023 dotkit <ewprjkt@proton.me>
#

image:
  file: .gitpod.dockerfile

tasks:
  - before: >
      [[ ! -z $GNUPG_KEY  ]] &&
      gpg --verbose --batch --import <(echo $GNUPG_KEY|base64 -d) &&
      echo 'pinentry-mode loopback' >> ~/.gnupg/gpg.conf
